### ISSUE TITLE
`Id` is present in `#/definitions` which is extra as per 2.0 spec

### ISSUE THREAD

**Issue by prat0318** [apigee-127/swagger-converter#10]
`id` should not be present in any of the `#/definitions` object.

Candidate Soln: prat0318/swagger-converter@2a4e2006bb442c81c31ee4f2847b559a235a3432

**Comment by mohsen1** [comment]
This looks good to me. If you make a PR with both changes you proposed it would be great!

**Comment by maver1ck** [comment]
Was this code merged into master branch ? 
I have the same problem.

**Comment by mohsen1** [comment]
@maver1ck can you make a PR with that change?

**Comment by maver1ck** [comment]
https://github.com/apigee-127/swagger-converter/pull/19

**Comment by mohsen1** [comment]
Merged
