### ISSUE TITLE
Need more information on 'Usage' section

### ISSUE THREAD

**Issue by ndhar-1** [apigee-127/swagger-converter#11]
The part explaining the usage of Swagger Converter is not very informative. I had troubles figuring out both the installation ways mentioned. For npm, I wasn't sure where to put those javascript statements. Then I realized I need a node to implement that, which I dont have. For the other one, with browser.js, I am still not able to get the desired result. Maybe I am calling the method incorrectly: var convert = SwaggerConverter.convert; ...... I am including this call in index.html of Swagger UI.

**Comment by prabhatjha** [comment]
Swagger-converter is used in swagger-tools and you can see how to use it at https://github.com/apigee-127/swagger-tools/blob/master/docs/API.md#convertresourcelisting-apideclarations-skipvalidation-callback

**Comment by ndhar-1** [comment]
Well this page should be referenced on the page for Swagger-Converter. I read the link you gave, it looks like all examples were for coding in Node.js. Is there an example on how to do it using browser.js ?

**Comment by mohsen1** [comment]
You need to have all swagger files in plain-old JavaScript objects and pass the root swagger object as first arguments and an array of objects (which are your other swagger files)  as second arguments. Please let me know what error you're getting when you're trying that

**Comment by ndhar-1** [comment]
Oh ok. I have Swagger resource files in JSON (spec 1.2) as is required by the Swagger UI. I thought this utility will help generate JSON files which comply with Swagger 2.0 spec given the spec 1.2 JSON files. I think I am mistaken here. Is it ?

**Comment by mohsen1** [comment]
First, parse the JSON strings to get the objects out.

Your resources files which you have as JSON should be passed as an array of objects and for the first argument send the main swagger file object.

For example if I want to convert petstore example I need to do the following 

Download and parse file at list resources (root file) 
Download and parse all resources files and push it to

**Comment by shubhamchaudhary** [comment]
Same problem. The description is really not informative at all. It will be really great if we can get a step by step usage information (which doesn't assume any technical knowledge).

**Comment by mohsen1** [comment]
@shubhamchaudhary Your usage here at https://github.com/apigee-127/swagger-converter/issues/15 is correct.

**Comment by whitlockjc** [comment]
I was able to use `swagger-converter` in `swagger-tools` without any issue based on the README.  It's a very simple API that is pretty well documented.  _(The example in the README is spot on and the API arguments are documented there too.)_  If you're wanting to have a CLI for converting Swagger 1.2 to Swagger 2.0, check out [swagger-tools](https://github.com/apigee-127/swagger-tools/blob/master/docs/CLI.md#convert).  Otherwise, I don't see how else to make the README any simpler in my opinion.

**Comment by ndhar-1** [comment]
Thank for the explanation mohsen1. I understand it. But actually I am working in Java codebase and thought to implement it there. I don't have Node.js. When I saw the following code, I thought I could implement this in the index.html of the Swagger UI and get the UI working with spec 2.0:

Include the browser.js script in your HTML

  <script src="/path/to/swagger-converter/browser.js"></script>
Use the script

var convert = SwaggerConverter.convert;

**Comment by mohsen1** [comment]
I've never used it in browser but there is nothing stopping it working in browser. What error are you getting?
