### ISSUE TITLE
Create Swagger Object and Operation tags during conversion

### ISSUE THREAD

**Issue by analogue** [apigee-127/swagger-converter#18]
Operations don't have tags when doing a conversion. This results in all operations being lumped into the "default" resource bucket in the swagger-ui for Swagger 2.0 instead of being nicely categorized like the swagger-ui for Swagger 1.2.

Basically, use a sanitized `#/apis/*/path` in the 1.2 schema as the operation tag and `#/apis/*/description` in the 1.2 schema as the Swagger Object tag description.

**Comment by mohsen1** [comment]
I don't think `description` can directly mapped to tags. @webron what do you think?

**Comment by webron** [comment]
What we (kinda) do with swagger-core is take the `path` from the Resource Listing (such as http://petstore.swagger.io/api/api-docs) and use that as the tag for the converted operations (that's a 1:1 conversion). The `description` can indeed be mapped to the top level `tags`.

**Comment by prat0318** [comment]
I have noticed that in the current `Swagger UI` version, tags for 1.2 are formed from each resource's `resourcePath` instead of resource_listing's `path`. I have raised a separate issue reg. this in swagger-ui. Meanwhile, if we want to keep 1-on-1 relationship between v1.2 and v2.0 then v1.2's `resourcePath` should be converted to v2.0's `tags` imo.

**Comment by IvanGoncharov** [comment]
@analogue @prat0318  After 8918e59 commit, this lib try to use `resourcePath` for tag names and `path` as fallback. It also always correctly match description from Resource Listing.
It will be part of next major release, be aware that library API was changed.

**Comment by IvanGoncharov** [comment]
@analogue @prat0318 `1.0.0` release brought feature described in my previous comment.
I'm closing issue, but feel free to reopen in case if you expect different behaviour.
