### ISSUE TITLE
New minor release(0.2.0)

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/swagger-converter#53]
I'm still working on API changes.
Meanwhile `master` stable enough + test coverage is very good.
On the other side it's confusing for other people.
Like for example this PR #52, author based his changes on last public release.
Can you make `0.2.0` release?

**Comment by IvanGoncharov** [comment]
And then new API changes will be ready we could follow with `1.0.0` release.

**Comment by mohsen1** [comment]
Ok makes sense. Will do it today.

**Comment by IvanGoncharov** [comment]
@mohsen1 I accidently add API changes into #51 
It's already in `master`, so before release you need to revert it.
It's last commit(b36ddee) so it should be easy.

**Comment by IvanGoncharov** [comment]
@mohsen1 Thanks for release
