### ISSUE TITLE
How to use this converter to convert from swagger 1.2 to 2.0?

### ISSUE THREAD

**Issue by vivekkiran** [apigee-127/swagger-converter#58]

**Comment by IvanGoncharov** [comment]
In [README](https://github.com/apigee-127/swagger-converter#usage):
>It's recommended to use command line tools like swagger-tools or swagger-spec-converter for converting your spec.

**Comment by IvanGoncharov** [comment]
@mohsen1 Can you close this issue?
@vivekkiran If you still have some questions. Please use [our gitter chat](https://gitter.im/apigee-127/swagger-converter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by mohsen1** [comment]
@IvanGoncharov just added you as a Collaborator so you can close issues or merge PRs.

**Comment by IvanGoncharov** [comment]
@mohsen1 Thanks, I promise to use my new powers for good and not evil :innocent:
