### ISSUE TITLE
Losing / in tag names

### ISSUE THREAD

**Issue by sb8244** [apigee-127/swagger-converter#64]
I see that this line of the code https://github.com/apigee-127/swagger-converter/blob/master/index.js#L200 removes everything before the last /. 

Is this done as a convenience, or is it the swagger 2.0 spec that the resourcePath can't have / in it? I believe a valid resource could be something like `root/nested` to describe a nested resource.

**Comment by IvanGoncharov** [comment]
@sb8244 It like that mostly for historical reasons, previously it was use to match apiDeclarations to their descriptions inside resourceListing.
I agree that we could missed relevant part of tags but I don't like every tag to have common prefix especially things like '.../' or something similar. Solution is to find largest common prefix among all `resourcePath` remove everything after last slash. And strip resulting string from all `resourcePath`.
Please make separate function to find and strip this prefix.
Also please update browser files in separate commit.
