### ISSUE TITLE
Missing field "type" for array model convert from 1.2 to 2.0

### ISSUE THREAD

**Issue by henryyonathan90** [apigee-127/swagger-converter#80]
Hi,

Need some help here, I am using swagger-codegen and by chance need to convert swagger 1.2 spec to 2.0 so I am using your library to do it.
Everything is working fine at first but now I am faced with an issue where the produced spec seems missing field "type".

So here is the source spec:

```
{
    "items": {
        "type": "ShippingCostRequest",
        "absoluteType": "ShippingCostRequest"
    },
    "absoluteType": "array",
    "name": "body",
    "description": "requestList",
    "defaultValue": "",
    "required": false,
    "allowMultiple": true,
    "paramType": "body",
    "paramAccess": null
}
```
and here is the corresponding result:

```
{
  "description": "requestList",
  "in": "body",
  "name": "body",
  "required": false,
  "schema": {
    "items": {
      "$ref": "#/definitions/ShippingCostRequest"
    }
  }
}
```
*rest of the json is omitted for simplicity.

Using this converted spec in swagger-codegen give me NPE and after I do some debugging, I found out there is missing field here that is: "type": "array"

After I add it:

```
{
  "description": "requestList",
  "in": "body",
  "name": "body",
  "required": false,
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/ShippingCostRequest"
    }
}
```
Then the codegen running fine.

Can you help for this?

Thanks before.

**Comment by IvanGoncharov** [comment]
@henryyonathan90 Your swagger 1.2 file is invalid, it should contain `type: array`, like here:
https://github.com/apigee-127/swagger-converter/blob/007de4d9244e21f51832fa3b7ae9b2148b06034f/test/output/complex-parameters-multi.json#L22-L27

I don't think we should support converting from invalid 1.2 files.
Both input and output are JSON files so please write your own script that adds missing `type` properties.
