### ISSUE TITLE
Id is not added in the info object.

### ISSUE THREAD

**Issue by prat0318** [apigee-127/swagger-converter#9]
`id` is a required property of `info` which is not present in the converted schema.

Soln: prat0318/swagger-converter@47737e3cc2f7457e11c3af3e5bed591199da17a0

**Comment by mohsen1** [comment]
I think you meant https://github.com/prat0318/swagger-converter/commit/2a4e2006bb442c81c31ee4f2847b559a235a3432

That looks good. Could you make a PR with that change?

**Comment by IvanGoncharov** [comment]
@mohsen1 Both patches:
https://github.com/prat0318/swagger-converter/commit/47737e3cc2f7457e11c3af3e5bed591199da17a0
and
https://github.com/prat0318/swagger-converter/commit/2a4e2006bb442c81c31ee4f2847b559a235a3432
made their way into `swagger-converter` so you can close this issue.

**Comment by mohsen1** [comment]
👍
